### ISSUE TITLE
did you even test it out because one of my friends says it does not work

### ISSUE THREAD

**Issue by Cxsmo-ai** [riolubruh/StereoSoundFixed#2]
did you even test it out because one of my friends says it does not work

**Comment by Cxsmo-ai** [comment]
also i tested it and it doesn't work

**Comment by riolubruh** [comment]
I literally can't test it, I don't have a stereo microphone :L

**Comment by riolubruh** [comment]
Though I had a feeling I got the module wrong, because there are multiple modules with similarly named functions, but there wasn't much of a way for me to test which one was the correct one. Sorry about that, I kinda just uploaded it once it had no errors since that's my only gauge of if it's working or not! XD

**Comment by Cxsmo-ai** [comment]
You could run a virtual audio cable into discord to test it and then use the Craig bot to record it so you can see if it works so you can instead test it yourself instead of uploading a broken one

**Comment by riolubruh** [comment]
i knew about VAC but thanks for the tip about Craig bot, I didn't know about that. i'll try to work on the plugin later today

**Comment by riolubruh** [comment]
For now I'll private the repo
